/**
 * The queue. Names and counts only — deliberately no GROK.md files here.
 *
 * A name earns a file when there is enough primary text to argue with: letters,
 * notebooks, transcripts, testimony. Fame is not a qualification, and nobody on
 * this list is alive.
 */
export type ComingShelf = {
  title: string;
  note: string;
  names: string[];
};

export const COMING: ComingShelf[] = [
  {
    title: "Science & mathematics",
    note: "People who wrote down what they did not yet understand.",
    names: [
      "Johannes Kepler",
      "Tycho Brahe",
      "Galileo Galilei",
      "Isaac Newton",
      "Gottfried Leibniz",
      "Leonhard Euler",
      "Carl Friedrich Gauss",
      "Emmy Noether",
      "Henri Poincaré",
      "Kurt Gödel",
      "John von Neumann",
      "Paul Dirac",
      "Werner Heisenberg",
      "Niels Bohr",
      "Erwin Schrödinger",
      "Lise Meitner",
      "Rosalind Franklin",
      "Barbara McClintock",
      "Dorothy Hodgkin",
      "Subrahmanyan Chandrasekhar",
      "Enrico Fermi",
      "J. Robert Oppenheimer",
      "Alfred Russel Wallace",
      "Gregor Mendel",
    ],
  },
  {
    title: "Engineers & builders",
    note: "The ones who had to be right in public, in iron.",
    names: [
      "Isambard Kingdom Brunel",
      "James Watt",
      "George Stephenson",
      "Thomas Telford",
      "Gustave Eiffel",
      "Sergei Korolev",
      "Wernher von Braun",
      "Wilbur Wright",
      "Orville Wright",
      "Amy Johnson",
      "Grace Hopper",
      "Vannevar Bush",
      "Douglas Engelbart",
      "Norbert Wiener",
    ],
  },
  {
    title: "Letters & essays",
    note: "Prose stylists with a grudge and a deadline.",
    names: [
      "Samuel Johnson",
      "James Boswell",
      "Jonathan Swift",
      "William Hazlitt",
      "Virginia Woolf",
      "Joan Didion",
      "James Baldwin",
      "Zora Neale Hurston",
      "Jorge Luis Borges",
      "Franz Kafka",
      "Anton Chekhov",
      "Fyodor Dostoevsky",
      "Leo Tolstoy",
      "Emily Dickinson",
      "Walt Whitman",
      "John Keats",
      "Sylvia Plath",
      "Flannery O'Connor",
      "Primo Levi",
      "Dorothy Parker",
      "Christopher Hitchens",
    ],
  },
  {
    title: "Philosophy",
    note: "Arguing is the whole job.",
    names: [
      "Socrates",
      "Epictetus",
      "Seneca",
      "Diogenes of Sinope",
      "Confucius",
      "Zhuangzi",
      "Laozi",
      "Baruch Spinoza",
      "David Hume",
      "Immanuel Kant",
      "Søren Kierkegaard",
      "Friedrich Nietzsche",
      "Mary Wollstonecraft",
      "William James",
      "Bertrand Russell",
      "Simone Weil",
      "Simone de Beauvoir",
      "Iris Murdoch",
    ],
  },
  {
    title: "Politics, power & protest",
    note: "Speech under pressure, with consequences attached.",
    names: [
      "Abraham Lincoln",
      "Frederick Douglass",
      "Sojourner Truth",
      "Harriet Tubman",
      "Ida B. Wells",
      "Thomas Paine",
      "Thomas Jefferson",
      "John Adams",
      "Abigail Adams",
      "Winston Churchill",
      "Eleanor Roosevelt",
      "Mahatma Gandhi",
      "Martin Luther King Jr.",
      "Malcolm X",
      "Nelson Mandela",
      "Rosa Luxemburg",
      "Emmeline Pankhurst",
      "Václav Havel",
    ],
  },
  {
    title: "War & strategy",
    note: "Handled as sources, not as heroes.",
    names: [
      "Sun Tzu",
      "Julius Caesar",
      "Hannibal Barca",
      "Napoleon Bonaparte",
      "Carl von Clausewitz",
      "Horatio Nelson",
      "Ulysses S. Grant",
      "William Tecumseh Sherman",
      "Erwin Rommel",
      "Georgy Zhukov",
      "T. E. Lawrence",
      "John Boyd",
    ],
  },
  {
    title: "Sport & the body",
    note: "Nerve, repetition, and what happens at the limit.",
    names: [
      "Jesse Owens",
      "Jack Johnson",
      "Sugar Ray Robinson",
      "Pelé",
      "Diego Maradona",
      "Kobe Bryant",
      "Arthur Ashe",
      "Emil Zátopek",
      "Roger Bannister",
      "Bobby Fischer",
      "José Raúl Capablanca",
      "Bill Shankly",
      "Brian Clough",
      "Vince Lombardi",
    ],
  },
  {
    title: "Art & craft",
    note: "Hands first, theory afterwards.",
    names: [
      "Vincent van Gogh",
      "Rembrandt van Rijn",
      "Michelangelo Buonarroti",
      "Katsushika Hokusai",
      "Frida Kahlo",
      "Georgia O'Keeffe",
      "Auguste Rodin",
      "Louise Bourgeois",
      "William Morris",
      "Josef Albers",
      "Le Corbusier",
      "Frank Lloyd Wright",
      "Eileen Gray",
      "Charles Eames",
      "Ray Eames",
      "Massimo Vignelli",
    ],
  },
  {
    title: "Music",
    note: "Time, discipline, and refusing the easy chord.",
    names: [
      "Johann Sebastian Bach",
      "Wolfgang Amadeus Mozart",
      "Ludwig van Beethoven",
      "Clara Schumann",
      "Duke Ellington",
      "Louis Armstrong",
      "Billie Holiday",
      "Nina Simone",
      "Miles Davis",
      "John Coltrane",
      "Glenn Gould",
      "Johnny Cash",
      "Leonard Cohen",
      "David Bowie",
    ],
  },
  {
    title: "Explorers & the wild",
    note: "Field notebooks beat memoirs every time.",
    names: [
      "Ernest Shackleton",
      "Roald Amundsen",
      "Robert Falcon Scott",
      "Alexander von Humboldt",
      "Mary Kingsley",
      "Gertrude Bell",
      "Freya Stark",
      "Thor Heyerdahl",
      "Jacques Cousteau",
      "John Muir",
      "Aldo Leopold",
      "Rachel Carson",
    ],
  },
  {
    title: "Medicine & the mind",
    note: "Bedside voices, including the ones who were wrong.",
    names: [
      "Hippocrates",
      "Galen",
      "Edward Jenner",
      "Ignaz Semmelweis",
      "Florence Nightingale",
      "William Osler",
      "Alexander Fleming",
      "Sigmund Freud",
      "Carl Jung",
      "Elisabeth Kübler-Ross",
      "Oliver Sacks",
      "Paul Farmer",
    ],
  },
  {
    title: "Money, work & trade",
    note: "Nobody here will tell you what to buy.",
    names: [
      "Adam Smith",
      "David Ricardo",
      "John Maynard Keynes",
      "Benjamin Graham",
      "Andrew Carnegie",
      "John D. Rockefeller",
      "Charlie Munger",
      "Peter Drucker",
      "W. Edwards Deming",
      "Taiichi Ohno",
    ],
  },
  {
    title: "Law & justice",
    note: "Argument as a craft with rules.",
    names: [
      "Marcus Tullius Cicero",
      "Hugo Grotius",
      "Cesare Beccaria",
      "Oliver Wendell Holmes Jr.",
      "Learned Hand",
      "Clarence Darrow",
      "Thurgood Marshall",
      "Ruth Bader Ginsburg",
    ],
  },
  {
    title: "Faith & doubt",
    note: "Handled as literature and testimony, never as instruction.",
    names: [
      "Augustine of Hippo",
      "Thomas Aquinas",
      "Julian of Norwich",
      "Meister Eckhart",
      "Rumi",
      "Teresa of Ávila",
      "Martin Luther",
      "Dietrich Bonhoeffer",
      "Thomas Merton",
      "Dorothy Day",
    ],
  },
  {
    title: "Stage, screen & the joke",
    note: "Timing is a moral position.",
    names: [
      "William Shakespeare",
      "Molière",
      "Henrik Ibsen",
      "Oscar Wilde",
      "Charlie Chaplin",
      "Buster Keaton",
      "Orson Welles",
      "Akira Kurosawa",
      "Richard Pryor",
      "George Carlin",
      "Peter Cook",
      "Victoria Wood",
    ],
  },
];

export const COMING_COUNT = COMING.reduce((total, shelf) => total + shelf.names.length, 0);
